// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/writerai/writer-client-sdk-go/pkg/models/shared"
	"net/http"
)

type AddTermsRequest struct {
	CreateTermsRequest shared.CreateTermsRequest `request:"mediaType=application/json"`
	TeamID             int64                     `pathParam:"style=simple,explode=false,name=teamId"`
	OrganizationID     *int64                    `pathParam:"style=simple,explode=false,name=organizationId"`
}

func (o *AddTermsRequest) GetCreateTermsRequest() shared.CreateTermsRequest {
	if o == nil {
		return shared.CreateTermsRequest{}
	}
	return o.CreateTermsRequest
}

func (o *AddTermsRequest) GetTeamID() int64 {
	if o == nil {
		return 0
	}
	return o.TeamID
}

func (o *AddTermsRequest) GetOrganizationID() *int64 {
	if o == nil {
		return nil
	}
	return o.OrganizationID
}

type AddTermsResponse struct {
	// HTTP response content type for this operation
	ContentType         string
	CreateTermsResponse *shared.CreateTermsResponse
	Headers             map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *AddTermsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *AddTermsResponse) GetCreateTermsResponse() *shared.CreateTermsResponse {
	if o == nil {
		return nil
	}
	return o.CreateTermsResponse
}

func (o *AddTermsResponse) GetHeaders() map[string][]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *AddTermsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *AddTermsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
