// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/writerai/writer-client-sdk-go/pkg/models/shared"
	"net/http"
)

type ContentCheckRequest struct {
	ContentRequest shared.ContentRequest `request:"mediaType=application/json"`
	TeamID         int64                 `pathParam:"style=simple,explode=false,name=teamId"`
	OrganizationID *int64                `pathParam:"style=simple,explode=false,name=organizationId"`
}

func (o *ContentCheckRequest) GetContentRequest() shared.ContentRequest {
	if o == nil {
		return shared.ContentRequest{}
	}
	return o.ContentRequest
}

func (o *ContentCheckRequest) GetTeamID() int64 {
	if o == nil {
		return 0
	}
	return o.TeamID
}

func (o *ContentCheckRequest) GetOrganizationID() *int64 {
	if o == nil {
		return nil
	}
	return o.OrganizationID
}

type ContentCheckResponse struct {
	// HTTP response content type for this operation
	ContentType      string
	Headers          map[string][]string
	ProcessedContent *shared.ProcessedContent
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *ContentCheckResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ContentCheckResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}

func (o *ContentCheckResponse) GetProcessedContent() *shared.ProcessedContent {
	if o == nil {
		return nil
	}
	return o.ProcessedContent
}

func (o *ContentCheckResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ContentCheckResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
