// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/writerai/writer-client-sdk-go/pkg/models/shared"
	"net/http"
)

type ContentCorrectRequest struct {
	ContentRequest shared.ContentRequest `request:"mediaType=application/json"`
	XRequestID     *string               `header:"style=simple,explode=false,name=X-Request-ID"`
	OrganizationID *int64                `pathParam:"style=simple,explode=false,name=organizationId"`
	TeamID         int64                 `pathParam:"style=simple,explode=false,name=teamId"`
}

func (o *ContentCorrectRequest) GetContentRequest() shared.ContentRequest {
	if o == nil {
		return shared.ContentRequest{}
	}
	return o.ContentRequest
}

func (o *ContentCorrectRequest) GetXRequestID() *string {
	if o == nil {
		return nil
	}
	return o.XRequestID
}

func (o *ContentCorrectRequest) GetOrganizationID() *int64 {
	if o == nil {
		return nil
	}
	return o.OrganizationID
}

func (o *ContentCorrectRequest) GetTeamID() int64 {
	if o == nil {
		return 0
	}
	return o.TeamID
}

type ContentCorrectResponse struct {
	// HTTP response content type for this operation
	ContentType        string
	CorrectionResponse *shared.CorrectionResponse
	Headers            map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *ContentCorrectResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ContentCorrectResponse) GetCorrectionResponse() *shared.CorrectionResponse {
	if o == nil {
		return nil
	}
	return o.CorrectionResponse
}

func (o *ContentCorrectResponse) GetHeaders() map[string][]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *ContentCorrectResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ContentCorrectResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
