// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/writerai/writer-client-sdk-go/pkg/models/shared"
	"net/http"
)

type CreateModelCustomizationRequest struct {
	CreateCustomizationRequest shared.CreateCustomizationRequest `request:"mediaType=application/json"`
	ModelID                    string                            `pathParam:"style=simple,explode=false,name=modelId"`
	OrganizationID             *int64                            `pathParam:"style=simple,explode=false,name=organizationId"`
}

func (o *CreateModelCustomizationRequest) GetCreateCustomizationRequest() shared.CreateCustomizationRequest {
	if o == nil {
		return shared.CreateCustomizationRequest{}
	}
	return o.CreateCustomizationRequest
}

func (o *CreateModelCustomizationRequest) GetModelID() string {
	if o == nil {
		return ""
	}
	return o.ModelID
}

func (o *CreateModelCustomizationRequest) GetOrganizationID() *int64 {
	if o == nil {
		return nil
	}
	return o.OrganizationID
}

type CreateModelCustomizationResponse struct {
	// HTTP response content type for this operation
	ContentType        string
	Headers            map[string][]string
	ModelCustomization *shared.ModelCustomization
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *CreateModelCustomizationResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateModelCustomizationResponse) GetHeaders() map[string][]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *CreateModelCustomizationResponse) GetModelCustomization() *shared.ModelCustomization {
	if o == nil {
		return nil
	}
	return o.ModelCustomization
}

func (o *CreateModelCustomizationResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateModelCustomizationResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
