// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/writerai/writer-client-sdk-go/pkg/models/shared"
	"net/http"
)

type CreateCompletionRequest struct {
	CompletionRequest shared.CompletionRequest `request:"mediaType=application/json"`
	ModelID           string                   `pathParam:"style=simple,explode=false,name=modelId"`
	OrganizationID    *int64                   `pathParam:"style=simple,explode=false,name=organizationId"`
}

type CreateCompletionResponse struct {
	CompletionResponse *shared.CompletionResponse
	ContentType        string
	// Bad Request
	FailResponse *shared.FailResponse
	Headers      map[string][]string
	StatusCode   int
	RawResponse  *http.Response
}
