// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteFileRequest struct {
	FileID         string `pathParam:"style=simple,explode=false,name=fileId"`
	OrganizationID *int64 `pathParam:"style=simple,explode=false,name=organizationId"`
}

func (o *DeleteFileRequest) GetFileID() string {
	if o == nil {
		return ""
	}
	return o.FileID
}

func (o *DeleteFileRequest) GetOrganizationID() *int64 {
	if o == nil {
		return nil
	}
	return o.OrganizationID
}

type DeleteFile200ApplicationJSON struct {
}

type DeleteFileResponse struct {
	// HTTP response content type for this operation
	ContentType string
	Headers     map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse                        *http.Response
	DeleteFile200ApplicationJSONObject *DeleteFile200ApplicationJSON
}

func (o *DeleteFileResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteFileResponse) GetHeaders() map[string][]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *DeleteFileResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteFileResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *DeleteFileResponse) GetDeleteFile200ApplicationJSONObject() *DeleteFile200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.DeleteFile200ApplicationJSONObject
}
