// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/writerai/writer-client-sdk-go/pkg/models/shared"
	"net/http"
)

type DeleteTermsRequest struct {
	XRequestID     *string `header:"style=simple,explode=false,name=X-Request-ID"`
	Ids            []int64 `queryParam:"style=form,explode=true,name=ids"`
	OrganizationID *int64  `pathParam:"style=simple,explode=false,name=organizationId"`
	TeamID         int64   `pathParam:"style=simple,explode=false,name=teamId"`
}

type DeleteTermsResponse struct {
	ContentType    string
	DeleteResponse *shared.DeleteResponse
	// Bad Request
	FailResponse *shared.FailResponse
	Headers      map[string][]string
	StatusCode   int
	RawResponse  *http.Response
}
