// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/writerai/writer-client-sdk-go/pkg/models/shared"
	"net/http"
)

type DetectContentRequest struct {
	ContentDetectorRequest shared.ContentDetectorRequest `request:"mediaType=application/json"`
	OrganizationID         *int64                        `pathParam:"style=simple,explode=false,name=organizationId"`
}

func (o *DetectContentRequest) GetContentDetectorRequest() shared.ContentDetectorRequest {
	if o == nil {
		return shared.ContentDetectorRequest{}
	}
	return o.ContentDetectorRequest
}

func (o *DetectContentRequest) GetOrganizationID() *int64 {
	if o == nil {
		return nil
	}
	return o.OrganizationID
}

type DetectContentResponse struct {
	// HTTP response content type for this operation
	ContentType string
	Headers     map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	Classes     []shared.ContentDetectorResponse
}

func (o *DetectContentResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DetectContentResponse) GetHeaders() map[string][]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *DetectContentResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DetectContentResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *DetectContentResponse) GetClasses() []shared.ContentDetectorResponse {
	if o == nil {
		return nil
	}
	return o.Classes
}
