// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/writerai/writer-client-sdk-go/pkg/models/shared"
	"net/http"
)

type DetectContentRequest struct {
	ContentDetectorRequest shared.ContentDetectorRequest `request:"mediaType=application/json"`
	OrganizationID         *int64                        `pathParam:"style=simple,explode=false,name=organizationId"`
}

type DetectContentResponse struct {
	ContentDetectorResponses []shared.ContentDetectorResponse
	ContentType              string
	// Bad Request
	FailResponse *shared.FailResponse
	Headers      map[string][]string
	StatusCode   int
	RawResponse  *http.Response
}
