// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/writerai/writer-client-sdk-go/pkg/models/shared"
	"net/http"
)

type FetchCustomizedModelFileRequest struct {
	CustomizationID string `pathParam:"style=simple,explode=false,name=customizationId"`
	ModelID         string `pathParam:"style=simple,explode=false,name=modelId"`
	OrganizationID  *int64 `pathParam:"style=simple,explode=false,name=organizationId"`
}

type FetchCustomizedModelFileResponse struct {
	ContentType string
	// Bad Request
	FailResponse                                                  *shared.FailResponse
	Headers                                                       map[string][]string
	StatusCode                                                    int
	RawResponse                                                   *http.Response
	FetchCustomizedModelFile200ApplicationOctetStreamBinaryString []byte
}
