// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/writerai/writer-client-sdk-go/pkg/models/shared"
	"net/http"
)

// FindSnippetsSortField
type FindSnippetsSortField string

const (
	FindSnippetsSortFieldShortcut         FindSnippetsSortField = "shortcut"
	FindSnippetsSortFieldCreationTime     FindSnippetsSortField = "creationTime"
	FindSnippetsSortFieldModificationTime FindSnippetsSortField = "modificationTime"
)

func (e FindSnippetsSortField) ToPointer() *FindSnippetsSortField {
	return &e
}

func (e *FindSnippetsSortField) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "shortcut":
		fallthrough
	case "creationTime":
		fallthrough
	case "modificationTime":
		*e = FindSnippetsSortField(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FindSnippetsSortField: %v", v)
	}
}

// FindSnippetsSortOrder
type FindSnippetsSortOrder string

const (
	FindSnippetsSortOrderAsc  FindSnippetsSortOrder = "asc"
	FindSnippetsSortOrderDesc FindSnippetsSortOrder = "desc"
)

func (e FindSnippetsSortOrder) ToPointer() *FindSnippetsSortOrder {
	return &e
}

func (e *FindSnippetsSortOrder) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "asc":
		fallthrough
	case "desc":
		*e = FindSnippetsSortOrder(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FindSnippetsSortOrder: %v", v)
	}
}

type FindSnippetsRequest struct {
	Limit          *int64                 `queryParam:"style=form,explode=true,name=limit"`
	Offset         *int64                 `queryParam:"style=form,explode=true,name=offset"`
	OrganizationID *int64                 `pathParam:"style=simple,explode=false,name=organizationId"`
	Search         *string                `queryParam:"style=form,explode=true,name=search"`
	Shortcuts      []string               `queryParam:"style=form,explode=true,name=shortcuts"`
	SortField      *FindSnippetsSortField `queryParam:"style=form,explode=true,name=sortField"`
	SortOrder      *FindSnippetsSortOrder `queryParam:"style=form,explode=true,name=sortOrder"`
	Tags           []string               `queryParam:"style=form,explode=true,name=tags"`
	TeamID         int64                  `pathParam:"style=simple,explode=false,name=teamId"`
}

type FindSnippetsResponse struct {
	ContentType string
	// Bad Request
	FailResponse                   *shared.FailResponse
	Headers                        map[string][]string
	PaginatedResultSnippetWithUser *shared.PaginatedResultSnippetWithUser
	StatusCode                     int
	RawResponse                    *http.Response
}
