// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/writerai/writer-client-sdk-go/pkg/models/shared"
	"net/http"
)

// FindTermsPartOfSpeechEnum
type FindTermsPartOfSpeechEnum string

const (
	FindTermsPartOfSpeechEnumNoun      FindTermsPartOfSpeechEnum = "noun"
	FindTermsPartOfSpeechEnumVerb      FindTermsPartOfSpeechEnum = "verb"
	FindTermsPartOfSpeechEnumAdverb    FindTermsPartOfSpeechEnum = "adverb"
	FindTermsPartOfSpeechEnumAdjective FindTermsPartOfSpeechEnum = "adjective"
)

func (e FindTermsPartOfSpeechEnum) ToPointer() *FindTermsPartOfSpeechEnum {
	return &e
}

func (e *FindTermsPartOfSpeechEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "noun":
		fallthrough
	case "verb":
		fallthrough
	case "adverb":
		fallthrough
	case "adjective":
		*e = FindTermsPartOfSpeechEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FindTermsPartOfSpeechEnum: %v", v)
	}
}

// FindTermsSortFieldEnum
type FindTermsSortFieldEnum string

const (
	FindTermsSortFieldEnumTerm             FindTermsSortFieldEnum = "term"
	FindTermsSortFieldEnumCreationTime     FindTermsSortFieldEnum = "creationTime"
	FindTermsSortFieldEnumModificationTime FindTermsSortFieldEnum = "modificationTime"
	FindTermsSortFieldEnumType             FindTermsSortFieldEnum = "type"
)

func (e FindTermsSortFieldEnum) ToPointer() *FindTermsSortFieldEnum {
	return &e
}

func (e *FindTermsSortFieldEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "term":
		fallthrough
	case "creationTime":
		fallthrough
	case "modificationTime":
		fallthrough
	case "type":
		*e = FindTermsSortFieldEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FindTermsSortFieldEnum: %v", v)
	}
}

// FindTermsSortOrderEnum
type FindTermsSortOrderEnum string

const (
	FindTermsSortOrderEnumAsc  FindTermsSortOrderEnum = "asc"
	FindTermsSortOrderEnumDesc FindTermsSortOrderEnum = "desc"
)

func (e FindTermsSortOrderEnum) ToPointer() *FindTermsSortOrderEnum {
	return &e
}

func (e *FindTermsSortOrderEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "asc":
		fallthrough
	case "desc":
		*e = FindTermsSortOrderEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FindTermsSortOrderEnum: %v", v)
	}
}

// FindTermsTypeEnum
type FindTermsTypeEnum string

const (
	FindTermsTypeEnumApproved FindTermsTypeEnum = "approved"
	FindTermsTypeEnumBanned   FindTermsTypeEnum = "banned"
	FindTermsTypeEnumPending  FindTermsTypeEnum = "pending"
)

func (e FindTermsTypeEnum) ToPointer() *FindTermsTypeEnum {
	return &e
}

func (e *FindTermsTypeEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "approved":
		fallthrough
	case "banned":
		fallthrough
	case "pending":
		*e = FindTermsTypeEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FindTermsTypeEnum: %v", v)
	}
}

type FindTermsRequest struct {
	Limit          *int64                     `queryParam:"style=form,explode=true,name=limit"`
	Offset         *int64                     `queryParam:"style=form,explode=true,name=offset"`
	OrganizationID *int64                     `pathParam:"style=simple,explode=false,name=organizationId"`
	PartOfSpeech   *FindTermsPartOfSpeechEnum `queryParam:"style=form,explode=true,name=partOfSpeech"`
	SortField      *FindTermsSortFieldEnum    `queryParam:"style=form,explode=true,name=sortField"`
	SortOrder      *FindTermsSortOrderEnum    `queryParam:"style=form,explode=true,name=sortOrder"`
	Tags           []string                   `queryParam:"style=form,explode=true,name=tags"`
	TeamID         int64                      `pathParam:"style=simple,explode=false,name=teamId"`
	Term           *string                    `queryParam:"style=form,explode=true,name=term"`
	Type           *FindTermsTypeEnum         `queryParam:"style=form,explode=true,name=type"`
}

type FindTermsResponse struct {
	ContentType string
	// Bad Request
	FailResponse                    *shared.FailResponse
	Headers                         map[string][]string
	PaginatedResultFullTermWithUser *shared.PaginatedResultFullTermWithUser
	StatusCode                      int
	RawResponse                     *http.Response
}
