// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/writerai/writer-client-sdk-go/pkg/models/shared"
	"net/http"
)

// FindSnippetsSortFieldEnum
type FindSnippetsSortFieldEnum string

const (
	FindSnippetsSortFieldEnumShortcut         FindSnippetsSortFieldEnum = "shortcut"
	FindSnippetsSortFieldEnumCreationTime     FindSnippetsSortFieldEnum = "creationTime"
	FindSnippetsSortFieldEnumModificationTime FindSnippetsSortFieldEnum = "modificationTime"
)

func (e FindSnippetsSortFieldEnum) ToPointer() *FindSnippetsSortFieldEnum {
	return &e
}

func (e *FindSnippetsSortFieldEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "shortcut":
		fallthrough
	case "creationTime":
		fallthrough
	case "modificationTime":
		*e = FindSnippetsSortFieldEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FindSnippetsSortFieldEnum: %v", v)
	}
}

// FindSnippetsSortOrderEnum
type FindSnippetsSortOrderEnum string

const (
	FindSnippetsSortOrderEnumAsc  FindSnippetsSortOrderEnum = "asc"
	FindSnippetsSortOrderEnumDesc FindSnippetsSortOrderEnum = "desc"
)

func (e FindSnippetsSortOrderEnum) ToPointer() *FindSnippetsSortOrderEnum {
	return &e
}

func (e *FindSnippetsSortOrderEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "asc":
		fallthrough
	case "desc":
		*e = FindSnippetsSortOrderEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FindSnippetsSortOrderEnum: %v", v)
	}
}

type FindSnippetsRequest struct {
	Limit          *int64                     `queryParam:"style=form,explode=true,name=limit"`
	Offset         *int64                     `queryParam:"style=form,explode=true,name=offset"`
	OrganizationID *int64                     `pathParam:"style=simple,explode=false,name=organizationId"`
	Search         *string                    `queryParam:"style=form,explode=true,name=search"`
	Shortcuts      []string                   `queryParam:"style=form,explode=true,name=shortcuts"`
	SortField      *FindSnippetsSortFieldEnum `queryParam:"style=form,explode=true,name=sortField"`
	SortOrder      *FindSnippetsSortOrderEnum `queryParam:"style=form,explode=true,name=sortOrder"`
	Tags           []string                   `queryParam:"style=form,explode=true,name=tags"`
	TeamID         int64                      `pathParam:"style=simple,explode=false,name=teamId"`
}

type FindSnippetsResponse struct {
	ContentType string
	// Bad Request
	FailResponse                   *shared.FailResponse
	Headers                        map[string][]string
	PaginatedResultSnippetWithUser *shared.PaginatedResultSnippetWithUser
	StatusCode                     int
	RawResponse                    *http.Response
}
