// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/writerai/writer-client-sdk-go/pkg/models/shared"
	"net/http"
)

type GenerateContentRequest struct {
	GenerateTemplateRequest shared.GenerateTemplateRequest `request:"mediaType=application/json"`
	OrganizationID          *int64                         `pathParam:"style=simple,explode=false,name=organizationId"`
	TeamID                  int64                          `pathParam:"style=simple,explode=false,name=teamId"`
}

type GenerateContentResponse struct {
	ContentType string
	Draft       *shared.Draft
	// Bad Request
	FailResponse *shared.FailResponse
	Headers      map[string][]string
	StatusCode   int
	RawResponse  *http.Response
}
