// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/writerai/writer-client-sdk-go/pkg/models/shared"
	"net/http"
)

type GetDocumentDetailsRequest struct {
	DocumentID     int64  `pathParam:"style=simple,explode=false,name=documentId"`
	TeamID         int64  `pathParam:"style=simple,explode=false,name=teamId"`
	OrganizationID *int64 `pathParam:"style=simple,explode=false,name=organizationId"`
}

func (o *GetDocumentDetailsRequest) GetDocumentID() int64 {
	if o == nil {
		return 0
	}
	return o.DocumentID
}

func (o *GetDocumentDetailsRequest) GetTeamID() int64 {
	if o == nil {
		return 0
	}
	return o.TeamID
}

func (o *GetDocumentDetailsRequest) GetOrganizationID() *int64 {
	if o == nil {
		return nil
	}
	return o.OrganizationID
}

type GetDocumentDetailsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	Document    *shared.Document
	Headers     map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetDocumentDetailsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetDocumentDetailsResponse) GetDocument() *shared.Document {
	if o == nil {
		return nil
	}
	return o.Document
}

func (o *GetDocumentDetailsResponse) GetHeaders() map[string][]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *GetDocumentDetailsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetDocumentDetailsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
