// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/writerai/writer-client-sdk-go/pkg/models/shared"
	"net/http"
)

type GetDocumentDetailsRequest struct {
	DocumentID     int64  `pathParam:"style=simple,explode=false,name=documentId"`
	OrganizationID *int64 `pathParam:"style=simple,explode=false,name=organizationId"`
	TeamID         int64  `pathParam:"style=simple,explode=false,name=teamId"`
}

type GetDocumentDetailsResponse struct {
	ContentType string
	Document    *shared.Document
	// Bad Request
	FailResponse *shared.FailResponse
	Headers      map[string][]string
	StatusCode   int
	RawResponse  *http.Response
}
