// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/writerai/writer-client-sdk-go/pkg/models/shared"
	"net/http"
)

type GetModelCustomizationRequest struct {
	CustomizationID string `pathParam:"style=simple,explode=false,name=customizationId"`
	ModelID         string `pathParam:"style=simple,explode=false,name=modelId"`
	OrganizationID  *int64 `pathParam:"style=simple,explode=false,name=organizationId"`
}

func (o *GetModelCustomizationRequest) GetCustomizationID() string {
	if o == nil {
		return ""
	}
	return o.CustomizationID
}

func (o *GetModelCustomizationRequest) GetModelID() string {
	if o == nil {
		return ""
	}
	return o.ModelID
}

func (o *GetModelCustomizationRequest) GetOrganizationID() *int64 {
	if o == nil {
		return nil
	}
	return o.OrganizationID
}

type GetModelCustomizationResponse struct {
	// HTTP response content type for this operation
	ContentType        string
	Headers            map[string][]string
	ModelCustomization *shared.ModelCustomization
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetModelCustomizationResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetModelCustomizationResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}

func (o *GetModelCustomizationResponse) GetModelCustomization() *shared.ModelCustomization {
	if o == nil {
		return nil
	}
	return o.ModelCustomization
}

func (o *GetModelCustomizationResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetModelCustomizationResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
