// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/writerai/writer-client-sdk-go/pkg/models/shared"
	"net/http"
)

type GetSubscriptionDetailsResponse struct {
	ContentType string
	// Bad Request
	FailResponse                  *shared.FailResponse
	Headers                       map[string][]string
	StatusCode                    int
	RawResponse                   *http.Response
	SubscriptionPublicResponseAPI *shared.SubscriptionPublicResponseAPI
}
