// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/writerai/writer-client-sdk-go/pkg/models/shared"
	"net/http"
)

type GetSubscriptionDetailsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	Headers     map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse                   *http.Response
	SubscriptionPublicResponseAPI *shared.SubscriptionPublicResponseAPI
}

func (o *GetSubscriptionDetailsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetSubscriptionDetailsResponse) GetHeaders() map[string][]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *GetSubscriptionDetailsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetSubscriptionDetailsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetSubscriptionDetailsResponse) GetSubscriptionPublicResponseAPI() *shared.SubscriptionPublicResponseAPI {
	if o == nil {
		return nil
	}
	return o.SubscriptionPublicResponseAPI
}
