// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/writerai/writer-client-sdk-go/pkg/models/shared"
	"net/http"
)

type ListTemplatesRequest struct {
	OrganizationID *int64 `pathParam:"style=simple,explode=false,name=organizationId"`
	TeamID         int64  `pathParam:"style=simple,explode=false,name=teamId"`
	TemplateID     string `pathParam:"style=simple,explode=false,name=templateId"`
}

type ListTemplatesResponse struct {
	ContentType string
	// Bad Request
	FailResponse            *shared.FailResponse
	Headers                 map[string][]string
	StatusCode              int
	RawResponse             *http.Response
	TemplateDetailsResponse *shared.TemplateDetailsResponse
}
