// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/writerai/writer-client-sdk-go/pkg/models/shared"
	"net/http"
)

type ListTeamDocumentsQueryParamSortField string

const (
	ListTeamDocumentsQueryParamSortFieldTitle            ListTeamDocumentsQueryParamSortField = "title"
	ListTeamDocumentsQueryParamSortFieldCreationTime     ListTeamDocumentsQueryParamSortField = "creationTime"
	ListTeamDocumentsQueryParamSortFieldModificationTime ListTeamDocumentsQueryParamSortField = "modificationTime"
	ListTeamDocumentsQueryParamSortFieldModifiedByMeTime ListTeamDocumentsQueryParamSortField = "modifiedByMeTime"
	ListTeamDocumentsQueryParamSortFieldOpenedByMeTime   ListTeamDocumentsQueryParamSortField = "openedByMeTime"
)

func (e ListTeamDocumentsQueryParamSortField) ToPointer() *ListTeamDocumentsQueryParamSortField {
	return &e
}

func (e *ListTeamDocumentsQueryParamSortField) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "title":
		fallthrough
	case "creationTime":
		fallthrough
	case "modificationTime":
		fallthrough
	case "modifiedByMeTime":
		fallthrough
	case "openedByMeTime":
		*e = ListTeamDocumentsQueryParamSortField(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListTeamDocumentsQueryParamSortField: %v", v)
	}
}

type ListTeamDocumentsQueryParamSortOrder string

const (
	ListTeamDocumentsQueryParamSortOrderAsc  ListTeamDocumentsQueryParamSortOrder = "asc"
	ListTeamDocumentsQueryParamSortOrderDesc ListTeamDocumentsQueryParamSortOrder = "desc"
)

func (e ListTeamDocumentsQueryParamSortOrder) ToPointer() *ListTeamDocumentsQueryParamSortOrder {
	return &e
}

func (e *ListTeamDocumentsQueryParamSortOrder) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "asc":
		fallthrough
	case "desc":
		*e = ListTeamDocumentsQueryParamSortOrder(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListTeamDocumentsQueryParamSortOrder: %v", v)
	}
}

type ListTeamDocumentsRequest struct {
	Limit          *int                                  `queryParam:"style=form,explode=true,name=limit"`
	Offset         *int64                                `queryParam:"style=form,explode=true,name=offset"`
	OrganizationID *int64                                `pathParam:"style=simple,explode=false,name=organizationId"`
	Search         *string                               `queryParam:"style=form,explode=true,name=search"`
	SortField      *ListTeamDocumentsQueryParamSortField `queryParam:"style=form,explode=true,name=sortField"`
	SortOrder      *ListTeamDocumentsQueryParamSortOrder `queryParam:"style=form,explode=true,name=sortOrder"`
	TeamID         int64                                 `pathParam:"style=simple,explode=false,name=teamId"`
}

func (o *ListTeamDocumentsRequest) GetLimit() *int {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ListTeamDocumentsRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

func (o *ListTeamDocumentsRequest) GetOrganizationID() *int64 {
	if o == nil {
		return nil
	}
	return o.OrganizationID
}

func (o *ListTeamDocumentsRequest) GetSearch() *string {
	if o == nil {
		return nil
	}
	return o.Search
}

func (o *ListTeamDocumentsRequest) GetSortField() *ListTeamDocumentsQueryParamSortField {
	if o == nil {
		return nil
	}
	return o.SortField
}

func (o *ListTeamDocumentsRequest) GetSortOrder() *ListTeamDocumentsQueryParamSortOrder {
	if o == nil {
		return nil
	}
	return o.SortOrder
}

func (o *ListTeamDocumentsRequest) GetTeamID() int64 {
	if o == nil {
		return 0
	}
	return o.TeamID
}

type ListTeamDocumentsResponse struct {
	BriefDocuments *shared.BriefDocuments
	// HTTP response content type for this operation
	ContentType string
	Headers     map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *ListTeamDocumentsResponse) GetBriefDocuments() *shared.BriefDocuments {
	if o == nil {
		return nil
	}
	return o.BriefDocuments
}

func (o *ListTeamDocumentsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListTeamDocumentsResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}

func (o *ListTeamDocumentsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListTeamDocumentsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
