// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/writerai/writer-client-sdk-go/pkg/models/shared"
	"net/http"
)

type ListModelsRequest struct {
	OrganizationID *int64 `pathParam:"style=simple,explode=false,name=organizationId"`
}

func (o *ListModelsRequest) GetOrganizationID() *int64 {
	if o == nil {
		return nil
	}
	return o.OrganizationID
}

type ListModelsResponse struct {
	// HTTP response content type for this operation
	ContentType              string
	GenerationModelsResponse *shared.GenerationModelsResponse
	Headers                  map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *ListModelsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListModelsResponse) GetGenerationModelsResponse() *shared.GenerationModelsResponse {
	if o == nil {
		return nil
	}
	return o.GenerationModelsResponse
}

func (o *ListModelsResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}

func (o *ListModelsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListModelsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
