// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/writerai/writer-client-sdk-go/pkg/models/shared"
	"net/http"
)

type UpdateTermsRequest struct {
	UpdateTermsRequest shared.UpdateTermsRequest `request:"mediaType=application/json"`
	XRequestID         *string                   `header:"style=simple,explode=false,name=X-Request-ID"`
	OrganizationID     *int64                    `pathParam:"style=simple,explode=false,name=organizationId"`
	TeamID             int64                     `pathParam:"style=simple,explode=false,name=teamId"`
}

type UpdateTermsResponse struct {
	ContentType         string
	CreateTermsResponse *shared.CreateTermsResponse
	// Bad Request
	FailResponse *shared.FailResponse
	Headers      map[string][]string
	StatusCode   int
	RawResponse  *http.Response
}
