// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/writerai/writer-client-sdk-go/pkg/models/shared"
	"net/http"
)

type UpdateTermsRequest struct {
	UpdateTermsRequest shared.UpdateTermsRequest `request:"mediaType=application/json"`
	TeamID             int64                     `pathParam:"style=simple,explode=false,name=teamId"`
	XRequestID         *string                   `header:"style=simple,explode=false,name=X-Request-ID"`
	OrganizationID     *int64                    `pathParam:"style=simple,explode=false,name=organizationId"`
}

func (o *UpdateTermsRequest) GetUpdateTermsRequest() shared.UpdateTermsRequest {
	if o == nil {
		return shared.UpdateTermsRequest{}
	}
	return o.UpdateTermsRequest
}

func (o *UpdateTermsRequest) GetTeamID() int64 {
	if o == nil {
		return 0
	}
	return o.TeamID
}

func (o *UpdateTermsRequest) GetXRequestID() *string {
	if o == nil {
		return nil
	}
	return o.XRequestID
}

func (o *UpdateTermsRequest) GetOrganizationID() *int64 {
	if o == nil {
		return nil
	}
	return o.OrganizationID
}

type UpdateTermsResponse struct {
	// HTTP response content type for this operation
	ContentType         string
	CreateTermsResponse *shared.CreateTermsResponse
	Headers             map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *UpdateTermsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateTermsResponse) GetCreateTermsResponse() *shared.CreateTermsResponse {
	if o == nil {
		return nil
	}
	return o.CreateTermsResponse
}

func (o *UpdateTermsResponse) GetHeaders() map[string][]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *UpdateTermsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateTermsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
