// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ApprovedTermExtensionCreate struct {
	Capitalize        bool `json:"capitalize"`
	FixCase           bool `json:"fixCase"`
	FixCommonMistakes bool `json:"fixCommonMistakes"`
}
