// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CompletionResponse struct {
	Choices []CompletionGenerationChoice `json:"choices,omitempty"`
}

func (o *CompletionResponse) GetChoices() []CompletionGenerationChoice {
	if o == nil {
		return nil
	}
	return o.Choices
}
