// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CompletionGenerationChoiceLogprobs struct {
	TextOffset    []int64             `json:"textOffset,omitempty"`
	TokenLogprobs []float64           `json:"tokenLogprobs,omitempty"`
	Tokens        []string            `json:"tokens,omitempty"`
	TopLogprobs   []map[string]string `json:"topLogprobs,omitempty"`
}

func (o *CompletionGenerationChoiceLogprobs) GetTextOffset() []int64 {
	if o == nil {
		return nil
	}
	return o.TextOffset
}

func (o *CompletionGenerationChoiceLogprobs) GetTokenLogprobs() []float64 {
	if o == nil {
		return nil
	}
	return o.TokenLogprobs
}

func (o *CompletionGenerationChoiceLogprobs) GetTokens() []string {
	if o == nil {
		return nil
	}
	return o.Tokens
}

func (o *CompletionGenerationChoiceLogprobs) GetTopLogprobs() []map[string]string {
	if o == nil {
		return nil
	}
	return o.TopLogprobs
}
