// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CompletionRequest struct {
	BestOf           *int64   `json:"bestOf,omitempty"`
	FrequencyPenalty *float64 `json:"frequencyPenalty,omitempty"`
	Logprobs         *int64   `json:"logprobs,omitempty"`
	MaxTokens        *int64   `json:"maxTokens,omitempty"`
	MinTokens        *int64   `json:"minTokens,omitempty"`
	N                *int64   `json:"n,omitempty"`
	PresencePenalty  *float64 `json:"presencePenalty,omitempty"`
	Prompt           string   `json:"prompt"`
	Stop             []string `json:"stop,omitempty"`
	Temperature      *float64 `json:"temperature,omitempty"`
	TopP             *float64 `json:"topP,omitempty"`
}

func (o *CompletionRequest) GetBestOf() *int64 {
	if o == nil {
		return nil
	}
	return o.BestOf
}

func (o *CompletionRequest) GetFrequencyPenalty() *float64 {
	if o == nil {
		return nil
	}
	return o.FrequencyPenalty
}

func (o *CompletionRequest) GetLogprobs() *int64 {
	if o == nil {
		return nil
	}
	return o.Logprobs
}

func (o *CompletionRequest) GetMaxTokens() *int64 {
	if o == nil {
		return nil
	}
	return o.MaxTokens
}

func (o *CompletionRequest) GetMinTokens() *int64 {
	if o == nil {
		return nil
	}
	return o.MinTokens
}

func (o *CompletionRequest) GetN() *int64 {
	if o == nil {
		return nil
	}
	return o.N
}

func (o *CompletionRequest) GetPresencePenalty() *float64 {
	if o == nil {
		return nil
	}
	return o.PresencePenalty
}

func (o *CompletionRequest) GetPrompt() string {
	if o == nil {
		return ""
	}
	return o.Prompt
}

func (o *CompletionRequest) GetStop() []string {
	if o == nil {
		return nil
	}
	return o.Stop
}

func (o *CompletionRequest) GetTemperature() *float64 {
	if o == nil {
		return nil
	}
	return o.Temperature
}

func (o *CompletionRequest) GetTopP() *float64 {
	if o == nil {
		return nil
	}
	return o.TopP
}
