// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ContentRequest struct {
	Content  string          `json:"content"`
	Settings ContentSettings `json:"settings"`
}
