// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type FailHandling string

const (
	FailHandlingAccumulate   FailHandling = "accumulate"
	FailHandlingValidate     FailHandling = "validate"
	FailHandlingSkip         FailHandling = "skip"
	FailHandlingValidateOnly FailHandling = "validateOnly"
)

func (e FailHandling) ToPointer() *FailHandling {
	return &e
}

func (e *FailHandling) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "accumulate":
		fallthrough
	case "validate":
		fallthrough
	case "skip":
		fallthrough
	case "validateOnly":
		*e = FailHandling(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FailHandling: %v", v)
	}
}

type CreateTermsRequest struct {
	FailHandling *FailHandling `json:"failHandling,omitempty"`
	Models       []TermCreate  `json:"models,omitempty"`
}

func (o *CreateTermsRequest) GetFailHandling() *FailHandling {
	if o == nil {
		return nil
	}
	return o.FailHandling
}

func (o *CreateTermsRequest) GetModels() []TermCreate {
	if o == nil {
		return nil
	}
	return o.Models
}
