// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// FailResponse - Bad Request
type FailResponse struct {
	Errors []FailMessage `json:"errors,omitempty"`
	Extras interface{}   `json:"extras"`
	Tpe    string        `json:"tpe"`
}

func (o *FailResponse) GetErrors() []FailMessage {
	if o == nil {
		return nil
	}
	return o.Errors
}

func (o *FailResponse) GetExtras() interface{} {
	if o == nil {
		return nil
	}
	return o.Extras
}

func (o *FailResponse) GetTpe() string {
	if o == nil {
		return ""
	}
	return o.Tpe
}
