// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// FailResponse - Bad Request
type FailResponse struct {
	Errors []FailMessage `json:"errors,omitempty"`
	Extras interface{}   `json:"extras"`
	Tpe    string        `json:"tpe"`
}
