// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type FullLinkedTermPos string

const (
	FullLinkedTermPosNoun      FullLinkedTermPos = "noun"
	FullLinkedTermPosVerb      FullLinkedTermPos = "verb"
	FullLinkedTermPosAdverb    FullLinkedTermPos = "adverb"
	FullLinkedTermPosAdjective FullLinkedTermPos = "adjective"
)

func (e FullLinkedTermPos) ToPointer() *FullLinkedTermPos {
	return &e
}

func (e *FullLinkedTermPos) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "noun":
		fallthrough
	case "verb":
		fallthrough
	case "adverb":
		fallthrough
	case "adjective":
		*e = FullLinkedTermPos(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FullLinkedTermPos: %v", v)
	}
}

type FullLinkedTerm struct {
	ApprovedTermExtension *ApprovedTermExtension `json:"approvedTermExtension,omitempty"`
	CaseSensitive         bool                   `json:"caseSensitive"`
	ID                    *int64                 `json:"id,omitempty"`
	LinkedTermID          int64                  `json:"linkedTermId"`
	Pos                   *FullLinkedTermPos     `json:"pos,omitempty"`
	Term                  string                 `json:"term"`
	TermID                int64                  `json:"termId"`
}
