// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type GenerateTemplateRequest struct {
	Inputs     []MagicRequestInput `json:"inputs,omitempty"`
	TemplateID string              `json:"templateId"`
}
