// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type HyperParameters struct {
	NumVirtualTokens int64 `json:"numVirtualTokens"`
}

func (o *HyperParameters) GetNumVirtualTokens() int64 {
	if o == nil {
		return 0
	}
	return o.NumVirtualTokens
}
