// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type InputType string

const (
	InputTypeTextbox  InputType = "textbox"
	InputTypeTextarea InputType = "textarea"
	InputTypeDropdown InputType = "dropdown"
)

func (e InputType) ToPointer() *InputType {
	return &e
}

func (e *InputType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "textbox":
		fallthrough
	case "textarea":
		fallthrough
	case "dropdown":
		*e = InputType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InputType: %v", v)
	}
}

type Input struct {
	Dynamic   bool      `json:"dynamic"`
	Help      *string   `json:"help,omitempty"`
	MaxFields *int64    `json:"maxFields,omitempty"`
	MinFields *int64    `json:"minFields,omitempty"`
	Name      string    `json:"name"`
	Options   []string  `json:"options,omitempty"`
	Required  bool      `json:"required"`
	Subtitle  *string   `json:"subtitle,omitempty"`
	Type      InputType `json:"type"`
	UnitCopy  *string   `json:"unitCopy,omitempty"`
}

func (o *Input) GetDynamic() bool {
	if o == nil {
		return false
	}
	return o.Dynamic
}

func (o *Input) GetHelp() *string {
	if o == nil {
		return nil
	}
	return o.Help
}

func (o *Input) GetMaxFields() *int64 {
	if o == nil {
		return nil
	}
	return o.MaxFields
}

func (o *Input) GetMinFields() *int64 {
	if o == nil {
		return nil
	}
	return o.MinFields
}

func (o *Input) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Input) GetOptions() []string {
	if o == nil {
		return nil
	}
	return o.Options
}

func (o *Input) GetRequired() bool {
	if o == nil {
		return false
	}
	return o.Required
}

func (o *Input) GetSubtitle() *string {
	if o == nil {
		return nil
	}
	return o.Subtitle
}

func (o *Input) GetType() InputType {
	if o == nil {
		return InputType("")
	}
	return o.Type
}

func (o *Input) GetUnitCopy() *string {
	if o == nil {
		return nil
	}
	return o.UnitCopy
}
