// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type InputTypeEnum string

const (
	InputTypeEnumTextbox  InputTypeEnum = "textbox"
	InputTypeEnumTextarea InputTypeEnum = "textarea"
	InputTypeEnumDropdown InputTypeEnum = "dropdown"
)

func (e InputTypeEnum) ToPointer() *InputTypeEnum {
	return &e
}

func (e *InputTypeEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "textbox":
		fallthrough
	case "textarea":
		fallthrough
	case "dropdown":
		*e = InputTypeEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InputTypeEnum: %v", v)
	}
}

type Input struct {
	Dynamic   bool          `json:"dynamic"`
	Help      *string       `json:"help,omitempty"`
	MaxFields *int64        `json:"maxFields,omitempty"`
	MinFields *int64        `json:"minFields,omitempty"`
	Name      string        `json:"name"`
	Options   []string      `json:"options,omitempty"`
	Required  bool          `json:"required"`
	Subtitle  *string       `json:"subtitle,omitempty"`
	Type      InputTypeEnum `json:"type"`
	UnitCopy  *string       `json:"unitCopy,omitempty"`
}
