// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type Tier string

const (
	TierEnterprise1 Tier = "enterprise-1"
	TierEnterprise2 Tier = "enterprise-2"
	TierEnterprise3 Tier = "enterprise-3"
	TierEnterprise4 Tier = "enterprise-4"
)

func (e Tier) ToPointer() *Tier {
	return &e
}

func (e *Tier) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "enterprise-1":
		fallthrough
	case "enterprise-2":
		fallthrough
	case "enterprise-3":
		fallthrough
	case "enterprise-4":
		*e = Tier(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Tier: %v", v)
	}
}

type MetaData struct {
	Portal        map[string]string `json:"portal"`
	Reporting     map[string]string `json:"reporting"`
	SnippetsCount int64             `json:"snippetsCount"`
	SsoAccess     bool              `json:"ssoAccess"`
	Styleguide    map[string]string `json:"styleguide"`
	TeamCount     int64             `json:"teamCount"`
	TermsCount    int64             `json:"termsCount"`
	Tier          *Tier             `json:"tier,omitempty"`
}

func (o *MetaData) GetPortal() map[string]string {
	if o == nil {
		return map[string]string{}
	}
	return o.Portal
}

func (o *MetaData) GetReporting() map[string]string {
	if o == nil {
		return map[string]string{}
	}
	return o.Reporting
}

func (o *MetaData) GetSnippetsCount() int64 {
	if o == nil {
		return 0
	}
	return o.SnippetsCount
}

func (o *MetaData) GetSsoAccess() bool {
	if o == nil {
		return false
	}
	return o.SsoAccess
}

func (o *MetaData) GetStyleguide() map[string]string {
	if o == nil {
		return map[string]string{}
	}
	return o.Styleguide
}

func (o *MetaData) GetTeamCount() int64 {
	if o == nil {
		return 0
	}
	return o.TeamCount
}

func (o *MetaData) GetTermsCount() int64 {
	if o == nil {
		return 0
	}
	return o.TermsCount
}

func (o *MetaData) GetTier() *Tier {
	if o == nil {
		return nil
	}
	return o.Tier
}
