// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ModelFilesResponse struct {
	Files []ModelFile `json:"files,omitempty"`
}

func (o *ModelFilesResponse) GetFiles() []ModelFile {
	if o == nil {
		return nil
	}
	return o.Files
}
