// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"time"
)

type PageWithSectionResponseStatus string

const (
	PageWithSectionResponseStatusLive    PageWithSectionResponseStatus = "live"
	PageWithSectionResponseStatusOffline PageWithSectionResponseStatus = "offline"
)

func (e PageWithSectionResponseStatus) ToPointer() *PageWithSectionResponseStatus {
	return &e
}

func (e *PageWithSectionResponseStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "live":
		fallthrough
	case "offline":
		*e = PageWithSectionResponseStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PageWithSectionResponseStatus: %v", v)
	}
}

type PageWithSectionResponse struct {
	Content   *string                       `json:"content,omitempty"`
	CreatedAt time.Time                     `json:"createdAt"`
	ID        int64                         `json:"id"`
	Order     int64                         `json:"order"`
	Section   *SectionInfo                  `json:"section,omitempty"`
	Status    PageWithSectionResponseStatus `json:"status"`
	Title     string                        `json:"title"`
	UpdatedAt time.Time                     `json:"updatedAt"`
	UpdatedBy *SimpleUser                   `json:"updatedBy,omitempty"`
	URL       string                        `json:"url"`
}
