// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"time"
)

type PageWithSectionResponseStatusEnum string

const (
	PageWithSectionResponseStatusEnumLive    PageWithSectionResponseStatusEnum = "live"
	PageWithSectionResponseStatusEnumOffline PageWithSectionResponseStatusEnum = "offline"
)

func (e *PageWithSectionResponseStatusEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "live":
		fallthrough
	case "offline":
		*e = PageWithSectionResponseStatusEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for PageWithSectionResponseStatusEnum: %s", s)
	}
}

type PageWithSectionResponse struct {
	Content   *string                           `json:"content,omitempty"`
	CreatedAt time.Time                         `json:"createdAt"`
	ID        int64                             `json:"id"`
	Order     int64                             `json:"order"`
	Section   *SectionInfo                      `json:"section,omitempty"`
	Status    PageWithSectionResponseStatusEnum `json:"status"`
	Title     string                            `json:"title"`
	UpdatedAt time.Time                         `json:"updatedAt"`
	UpdatedBy *SimpleUser                       `json:"updatedBy,omitempty"`
	URL       string                            `json:"url"`
}
