// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PaginatedResultSnippetWithUser struct {
	Pagination Pagination        `json:"pagination"`
	Result     []SnippetWithUser `json:"result,omitempty"`
	TotalCount int64             `json:"totalCount"`
}
