// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PaginatedResultFullTermWithUser struct {
	Pagination Pagination         `json:"pagination"`
	Result     []FullTermWithUser `json:"result,omitempty"`
	TotalCount int64              `json:"totalCount"`
}
