// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PaginatedResultPagePublicAPIResponse struct {
	Pagination Pagination              `json:"pagination"`
	Result     []PagePublicAPIResponse `json:"result,omitempty"`
	TotalCount int64                   `json:"totalCount"`
}

func (o *PaginatedResultPagePublicAPIResponse) GetPagination() Pagination {
	if o == nil {
		return Pagination{}
	}
	return o.Pagination
}

func (o *PaginatedResultPagePublicAPIResponse) GetResult() []PagePublicAPIResponse {
	if o == nil {
		return nil
	}
	return o.Result
}

func (o *PaginatedResultPagePublicAPIResponse) GetTotalCount() int64 {
	if o == nil {
		return 0
	}
	return o.TotalCount
}
