// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type SectionInfo struct {
	ID    int64  `json:"id"`
	Title string `json:"title"`
	URL   string `json:"url"`
}

func (o *SectionInfo) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *SectionInfo) GetTitle() string {
	if o == nil {
		return ""
	}
	return o.Title
}

func (o *SectionInfo) GetURL() string {
	if o == nil {
		return ""
	}
	return o.URL
}
