// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type SimpleUser struct {
	Email     *string `json:"email,omitempty"`
	FirstName string  `json:"firstName"`
	ID        int64   `json:"id"`
	LastName  *string `json:"lastName,omitempty"`
}

func (o *SimpleUser) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *SimpleUser) GetFirstName() string {
	if o == nil {
		return ""
	}
	return o.FirstName
}

func (o *SimpleUser) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *SimpleUser) GetLastName() *string {
	if o == nil {
		return nil
	}
	return o.LastName
}
