// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type SnippetUpdate struct {
	Description *string        `json:"description,omitempty"`
	ID          string         `json:"id"`
	Shortcut    *string        `json:"shortcut,omitempty"`
	Snippet     string         `json:"snippet"`
	Tags        []SnippetTagV2 `json:"tags,omitempty"`
}
