// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type TermTagResponse struct {
	ID          int64  `json:"id"`
	ParentTagID int64  `json:"parentTagId"`
	Tag         string `json:"tag"`
	TermID      int64  `json:"termId"`
}

func (o *TermTagResponse) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *TermTagResponse) GetParentTagID() int64 {
	if o == nil {
		return 0
	}
	return o.ParentTagID
}

func (o *TermTagResponse) GetTag() string {
	if o == nil {
		return ""
	}
	return o.Tag
}

func (o *TermTagResponse) GetTermID() int64 {
	if o == nil {
		return 0
	}
	return o.TermID
}
