// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type TermCreatePosEnum string

const (
	TermCreatePosEnumNoun      TermCreatePosEnum = "noun"
	TermCreatePosEnumVerb      TermCreatePosEnum = "verb"
	TermCreatePosEnumAdverb    TermCreatePosEnum = "adverb"
	TermCreatePosEnumAdjective TermCreatePosEnum = "adjective"
)

func (e *TermCreatePosEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "noun":
		fallthrough
	case "verb":
		fallthrough
	case "adverb":
		fallthrough
	case "adjective":
		*e = TermCreatePosEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for TermCreatePosEnum: %s", s)
	}
}

type TermCreateTypeEnum string

const (
	TermCreateTypeEnumApproved TermCreateTypeEnum = "approved"
	TermCreateTypeEnumBanned   TermCreateTypeEnum = "banned"
	TermCreateTypeEnumPending  TermCreateTypeEnum = "pending"
)

func (e *TermCreateTypeEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "approved":
		fallthrough
	case "banned":
		fallthrough
	case "pending":
		*e = TermCreateTypeEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for TermCreateTypeEnum: %s", s)
	}
}

type TermCreate struct {
	ApprovedTermExtension *ApprovedTermExtensionCreate `json:"approvedTermExtension,omitempty"`
	CaseSensitive         bool                         `json:"caseSensitive"`
	Description           *string                      `json:"description,omitempty"`
	Examples              []TermExampleCreate          `json:"examples,omitempty"`
	Highlight             *bool                        `json:"highlight,omitempty"`
	LinkedTerms           []LinkedTermCreate           `json:"linkedTerms,omitempty"`
	Mistakes              []TermMistakeCreate          `json:"mistakes,omitempty"`
	Pos                   *TermCreatePosEnum           `json:"pos,omitempty"`
	Reference             *string                      `json:"reference,omitempty"`
	Tags                  []TermTagCreate              `json:"tags,omitempty"`
	Term                  string                       `json:"term"`
	Type                  TermCreateTypeEnum           `json:"type"`
}
