// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type TermExampleTypeEnum string

const (
	TermExampleTypeEnumGood TermExampleTypeEnum = "good"
	TermExampleTypeEnumBad  TermExampleTypeEnum = "bad"
)

func (e TermExampleTypeEnum) ToPointer() *TermExampleTypeEnum {
	return &e
}

func (e *TermExampleTypeEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "good":
		fallthrough
	case "bad":
		*e = TermExampleTypeEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TermExampleTypeEnum: %v", v)
	}
}

type TermExample struct {
	Example    string              `json:"example"`
	ID         *int64              `json:"id,omitempty"`
	TermBankID int64               `json:"termBankId"`
	TermID     int64               `json:"termId"`
	Type       TermExampleTypeEnum `json:"type"`
}
