// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type TermUpdatePosEnum string

const (
	TermUpdatePosEnumNoun      TermUpdatePosEnum = "noun"
	TermUpdatePosEnumVerb      TermUpdatePosEnum = "verb"
	TermUpdatePosEnumAdverb    TermUpdatePosEnum = "adverb"
	TermUpdatePosEnumAdjective TermUpdatePosEnum = "adjective"
)

func (e *TermUpdatePosEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "noun":
		fallthrough
	case "verb":
		fallthrough
	case "adverb":
		fallthrough
	case "adjective":
		*e = TermUpdatePosEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for TermUpdatePosEnum: %s", s)
	}
}

type TermUpdateTypeEnum string

const (
	TermUpdateTypeEnumApproved TermUpdateTypeEnum = "approved"
	TermUpdateTypeEnumBanned   TermUpdateTypeEnum = "banned"
	TermUpdateTypeEnumPending  TermUpdateTypeEnum = "pending"
)

func (e *TermUpdateTypeEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "approved":
		fallthrough
	case "banned":
		fallthrough
	case "pending":
		*e = TermUpdateTypeEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for TermUpdateTypeEnum: %s", s)
	}
}

type TermUpdate struct {
	ApprovedTermExtension *ApprovedTermExtensionCreate `json:"approvedTermExtension,omitempty"`
	CaseSensitive         bool                         `json:"caseSensitive"`
	Description           *string                      `json:"description,omitempty"`
	Examples              []TermExampleCreate          `json:"examples,omitempty"`
	Highlight             *bool                        `json:"highlight,omitempty"`
	ID                    int64                        `json:"id"`
	LinkedTerms           []LinkedTermCreate           `json:"linkedTerms,omitempty"`
	Mistakes              []TermMistakeCreate          `json:"mistakes,omitempty"`
	Pos                   *TermUpdatePosEnum           `json:"pos,omitempty"`
	Tags                  []TermTagCreate              `json:"tags,omitempty"`
	Term                  string                       `json:"term"`
	Type                  TermUpdateTypeEnum           `json:"type"`
}
