// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type UpdateTermsRequestFailHandlingEnum string

const (
	UpdateTermsRequestFailHandlingEnumAccumulate   UpdateTermsRequestFailHandlingEnum = "accumulate"
	UpdateTermsRequestFailHandlingEnumValidate     UpdateTermsRequestFailHandlingEnum = "validate"
	UpdateTermsRequestFailHandlingEnumSkip         UpdateTermsRequestFailHandlingEnum = "skip"
	UpdateTermsRequestFailHandlingEnumValidateOnly UpdateTermsRequestFailHandlingEnum = "validateOnly"
)

func (e UpdateTermsRequestFailHandlingEnum) ToPointer() *UpdateTermsRequestFailHandlingEnum {
	return &e
}

func (e *UpdateTermsRequestFailHandlingEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "accumulate":
		fallthrough
	case "validate":
		fallthrough
	case "skip":
		fallthrough
	case "validateOnly":
		*e = UpdateTermsRequestFailHandlingEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpdateTermsRequestFailHandlingEnum: %v", v)
	}
}

type UpdateTermsRequest struct {
	FailHandling *UpdateTermsRequestFailHandlingEnum `json:"failHandling,omitempty"`
	Models       []TermUpdate                        `json:"models,omitempty"`
}
