// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/writerai/writer-client-sdk-go/pkg/utils"
	"time"
)

type AccountStatus string

const (
	AccountStatusInvited  AccountStatus = "invited"
	AccountStatusSignedUp AccountStatus = "signed_up"
)

func (e AccountStatus) ToPointer() *AccountStatus {
	return &e
}

func (e *AccountStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "invited":
		fallthrough
	case "signed_up":
		*e = AccountStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AccountStatus: %v", v)
	}
}

type UserPublicResponse struct {
	AccountStatus  AccountStatus `json:"accountStatus"`
	Avatar         *string       `json:"avatar,omitempty"`
	CreatedAt      time.Time     `json:"createdAt"`
	Email          *string       `json:"email,omitempty"`
	FirstName      string        `json:"firstName"`
	FullName       string        `json:"fullName"`
	ID             int64         `json:"id"`
	InvitedBy      *int64        `json:"invitedBy,omitempty"`
	LastName       *string       `json:"lastName,omitempty"`
	LastSeenOnline *time.Time    `json:"lastSeenOnline,omitempty"`
	Timezone       *string       `json:"timezone,omitempty"`
}

func (u UserPublicResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UserPublicResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *UserPublicResponse) GetAccountStatus() AccountStatus {
	if o == nil {
		return AccountStatus("")
	}
	return o.AccountStatus
}

func (o *UserPublicResponse) GetAvatar() *string {
	if o == nil {
		return nil
	}
	return o.Avatar
}

func (o *UserPublicResponse) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *UserPublicResponse) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *UserPublicResponse) GetFirstName() string {
	if o == nil {
		return ""
	}
	return o.FirstName
}

func (o *UserPublicResponse) GetFullName() string {
	if o == nil {
		return ""
	}
	return o.FullName
}

func (o *UserPublicResponse) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *UserPublicResponse) GetInvitedBy() *int64 {
	if o == nil {
		return nil
	}
	return o.InvitedBy
}

func (o *UserPublicResponse) GetLastName() *string {
	if o == nil {
		return nil
	}
	return o.LastName
}

func (o *UserPublicResponse) GetLastSeenOnline() *time.Time {
	if o == nil {
		return nil
	}
	return o.LastSeenOnline
}

func (o *UserPublicResponse) GetTimezone() *string {
	if o == nil {
		return nil
	}
	return o.Timezone
}
